# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: pipeline-variables

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: echo Hello, Azure!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    echo "kronka: " $(spam)
    echo "kronka: " $(kronka)
  displayName: 'Access variables'

- script: |
    pwd
    git config --global user.email "cdeil-azure-pipelines@dummy.com"
    git config --global user.name "cdeil-azure-pipelines"
    git checkout -b spam
    echo `date` > date.txt
    git add date.txt
    git commit -am "update date.txt"
    echo "GithubPAT: " $(GithubPAT)
    git push https://$(GithubPAT)@github.com/cdeil/azure-pipelines-test.git spam
  displayName: 'Make a commit and push to github'
