# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: pipeline-variables

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: echo Hello, Azure!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    echo "kronka: " $(spam)
    echo "kronka: " $(kronka)
  displayName: 'Access variables'

# This is following the example from this blog post:
# http://blog.kaikeru.com/post/20181228-freestaticsite/
- script: |
    git config --global user.email "cdeil-azure-pipelines@dummy.com"
    git config --global user.name "cdeil-azure-pipelines"
    git clone https://$(github.username):$(github.token)@github.com/cdeil/azure-pipelines-test-visual.git /tmp/repo
    cd /tmp/repo
    echo `date` > date.txt
    git add date.txt
    git commit -m 'Autocommit from $(Build.DefinitionName) $(Build.BuildNumber)'
    git push origin
  displayName: 'Make a commit and push to github'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
